Use Feign for Retz client.
retz/retz pull request #95
Opened 2016-12-07 05:50 UTC by ueshin

This pr modifies retz-client to use Feign to handle HTTP access to retz-server.

Related issue: #45.

2016-12-07 07:13 UTC, kuenishi commented
On `make inttest`, 
```
io.github.retz.inttest.RetzIntTest > tooMuchResourceRequested FAILED                        
    java.io.IOException: status 400 reading Server#schedule(ScheduleRequest); content:                        
    Job {id=0, name=-1917737383, appid=echo, cmd=echo 42, env={}, cpus=1024, mem=32, priority=0, state=CREATED, reason=null, taskid=null} does not fit system $
imit {cpu=8,mem=31744MB,gpu=0,ports=10,disk=1024MB}                                                           
        at io.github.retz.web.feign.Server.tryOrErrorResponse(Server.java:112)                                
        at io.github.retz.web.Client.schedule(Client.java:86)                                                                            
        at io.github.retz.inttest.RetzIntTest.tooMuchResourceRequested(RetzIntTest.java:475)                                
                                                                                                                                                                       Caused by:                                                                                                                                                     feign.FeignException: status 400 reading Server#schedule(ScheduleRequest); content:                                                                            Job {id=0, name=-1917737383, appid=echo, cmd=echo 42, env={}, cpus=1024, mem=32, priority=0, state=CREATED, reason=null, taskid=null} does not fit sys$em limit {cpu=8,mem=31744MB,gpu=0,ports=10,disk=1024MB}                                                         
            at feign.FeignException.errorStatus(FeignException.java:62)                                                         
            at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:91)                                             
            at io.github.retz.web.feign.ErrorResponseDecoder.decode(ErrorResponseDecoder.java:53)                    
            at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
            at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
            at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
            at com.sun.proxy.$Proxy25.schedule(Unknown Source)
            at io.github.retz.web.feign.Server.schedule(Server.java:48)
            at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
            at feign.DefaultMethodHandler.invoke(DefaultMethodHandler.java:60)
            at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
            at com.sun.proxy.$Proxy25.schedule(Unknown Source)
            at io.github.retz.web.Client.lambda$schedule$1(Client.java:86)
            at io.github.retz.web.feign.Server.tryOrErrorResponse(Server.java:108)
            ... 2 more
```

2016-12-07 07:49 UTC, kuenishi commented on retz-client/src/main/java/io/github/retz/web/feign/Server.java
> +public interface Server {
Name like "Retz" or "RetzAPI" would be more suitable as the name of this interface according to [samples](https://github.com/OpenFeign/feign/blob/master/README.md) .

```java
GitHub github = Feign.builder()
                     .encoder(new JacksonEncoder())
                     .decoder(new JacksonDecoder())
                     .target(GitHub.class, "https://api.github.com");
```

2016-12-08 04:49 UTC, kuenishi requested changes

2016-12-08 04:49 UTC, kuenishi commented on retz-client/src/main/java/io/github/retz/web/Client.java
> +        this.server = Server.connect(uri, authenticator);
Does this initiates TCP (TLS) connection? If so, this should be after disabling TLS, in `protected Client(URI uri, Authenticator authenticator, boolean checkCert)` . In cases like testing, untrusted TLS trustfiles are to be used.

2016-12-08 04:49 UTC, kuenishi commented on retz-client/src/main/java/io/github/retz/web/feign/Server.java
> +public interface Server {
Name like "Retz" or "RetzAPI" would be more suitable as the name of this interface according to [samples](https://github.com/OpenFeign/feign/blob/master/README.md) .

```java
GitHub github = Feign.builder()
                     .encoder(new JacksonEncoder())
                     .decoder(new JacksonDecoder())
                     .target(GitHub.class, "https://api.github.com");
```

2016-12-08 04:49 UTC, kuenishi commented on retz-client/src/main/java/io/github/retz/web/feign/Server.java
> +            @Param("path") String path,
What happens if this parameter is `null`?

2016-12-08 08:14 UTC, ueshin commented on retz-client/src/main/java/io/github/retz/web/Client.java
> +        this.server = Server.connect(uri, authenticator);
The actual connection will be done later but I'd modify to `connect` later because I'm not sure the `server` object is thread-safe or not.

2016-12-08 08:15 UTC, ueshin commented on retz-client/src/main/java/io/github/retz/web/feign/Server.java
> +public interface Server {
I see, I'll use `Retz`.

2016-12-08 08:59 UTC, kuenishi approved these changes

2016-12-08 09:35 UTC, ueshin commented on retz-client/src/main/java/io/github/retz/web/feign/Server.java
> +            @Param("path") String path,
It looks working without the query parameter `path`, e.g. `GET /job/1/file?offset=0&length=100`.
If we want to null/required-check, we need to do it before call this request.
I'll modify to null/required-check in `Client` class.

2016-12-08 09:48 UTC, ueshin commented on retz-client/src/main/java/io/github/retz/web/feign/Server.java
> +            @Param("path") String path,
I found that there are some cases that the `@JsonProperty` says `required = true` but the `Request` doesn't null-check, e.g. `GetAppRequest` or `LoadAppRequest`, and `UnloadAppRequest`.
Should I null-check or not for the cases?

2016-12-08 10:18 UTC, ueshin commented on retz-client/src/main/java/io/github/retz/web/feign/Server.java
> +            @Param("path") String path,
I'd add null-checking for those cases for now.
Please let me know if we don't need them.

2016-12-09 05:14 UTC, merged